name: testing_app
description: A sample that shows testing in Flutter.

version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  provider: ^6.0.2
  go_router: ">=10.0.0 <13.0.0"
  firebase_core: ^2.24.0
  firebase_analytics: ^10.7.2
  growingio_autotracker_flutter_plugin: '1.1.3'

dev_dependencies:
  analysis_defaults:
    path: ../analysis_defaults
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  test: ^1.16.8

flutter:
  uses-material-design: true
