// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDorC2UM3wp7SwvPZc8Lp1sH_lnHryOm1Q',
    appId: '1:473515417490:web:05890815a92c8a22d82b4b',
    messagingSenderId: '473515417490',
    projectId: 'fa-demo-aabb2',
    authDomain: 'fa-demo-aabb2.firebaseapp.com',
    storageBucket: 'fa-demo-aabb2.appspot.com',
    measurementId: 'G-DHKFY6N3H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZbSyXE8JPCYqgQ9EjJ1g86zG0VzPpPKc',
    appId: '1:473515417490:android:976c26a95154ab8bd82b4b',
    messagingSenderId: '473515417490',
    projectId: 'fa-demo-aabb2',
    storageBucket: 'fa-demo-aabb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkVBTHWRDRgSOSSvvxDzvNmQeEz9gaChk',
    appId: '1:473515417490:ios:0d5bcf96acd4d7f2d82b4b',
    messagingSenderId: '473515417490',
    projectId: 'fa-demo-aabb2',
    storageBucket: 'fa-demo-aabb2.appspot.com',
    iosBundleId: 'dev.flutter.testingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkVBTHWRDRgSOSSvvxDzvNmQeEz9gaChk',
    appId: '1:473515417490:ios:b5727c153e0a2779d82b4b',
    messagingSenderId: '473515417490',
    projectId: 'fa-demo-aabb2',
    storageBucket: 'fa-demo-aabb2.appspot.com',
    iosBundleId: 'dev.flutter.testingApp.RunnerTests',
  );
}
